name: bs_mobile
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.5
  flutter_launcher_icons: ^0.14.3
  flutter_dotenv: ^5.2.1
  logger: ^2.5.0
  google_sign_in: ^6.3.0
  flutter_secure_storage: ^9.2.4
  sqflite: ^2.4.2
  shimmer: ^3.0.0
  go_router: ^14.8.1
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  dio: ^5.8.0+1
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true

  assets:
    # - assets/images/logo.png
    - assets/images/logo2.png
fonts:
  - family: IconFont
    fonts:
      - asset: assets/fonts/iconfont.ttf

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#000000"
  image: assets/images/logo2.png

  android: true
  ios: true

flutter_icons:
  image_path: "assets/images/logo2.png"
  android: true
  ios: true
