services:
  bs_backend:
    container_name: bs-backend
    build: . 
    image: bs-backend:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:8000"
    volumes:
      - .:/bs_backend
    networks:
      - bs-network
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "3"

networks:
  bs-network: