# Generated by Django 5.1.6 on 2025-03-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('avatar', models.CharField(help_text='头像文件名', max_length=255)),
            ],
            options={
                'db_table': 'user',
                'ordering': ['-id'],
            },
        ),
    ]
