# Generated by Django 5.1.6 on 2025-03-24 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0002_alter_snippetlabel_owner'),
        ('user', '0002_alter_user_managers_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='user.user'),
        ),
    ]
